### ISSUE TITLE
Remove deprecated features

### ISSUE THREAD

**Issue by braingram** [asdf-format/asdf#1698]
This issue is to track deprecated features that are scheduled for removal in asdf `4.0.0`:
- [ ] `asdf.util.human_list` (deprecated: #1688)
- [ ] `asdf.util.resolve_name` (deprecated: #1688)
- [ ] `asdf.util.minversion` (deprecated: #1688)
- [ ] `asdf.util.iter_subclasses` (deprecated: #1688)
