### ISSUE TITLE
Deprecations to be removed in ASDF 3.0

### ISSUE THREAD

**Issue by drdavella** [asdf-format/asdf#588]
This issue should be used to track any deprecated features that will need to be removed entirely in the 3.0 release.

* [x] Remove the `AsdfFile.open` method (deprecated in #579)
* [x] Remove `AsdfFile.tag_to_schema_resolver` and `AsdfExtensionList.tag_to_schema_resolver` (deprecated in #399)
* [x] Remove `asdf.asdftypes` now that it has been replaced by `asdf.types` (deprecated in #611)
* [x] Remove `resolvers.default_url_mapping`, `resolvers.default_tag_to_url_mapping`, and `resolvers.default_resolver` (deprecated in #682)
* [x] Remove `extension.default_ext_resolver` (deprecated in #682)
* [x] Remove `resolver.Resolver.add_mapping` (deprecated in #682)
* [ ] Remove `software` property in `ExtensionMetadata` (deprecated in #728)
* [x] Remove `asdf.schema.load_custom_schema` (deprecated in #738)
* [x] Remove argument `resolve_local_refs=True` in function call `load_schema()` (deprecated in #738)

**Comment by stscijgbot** [comment]
This ticket is now being tracked at [AL-114](https://jira.stsci.edu/browse/AL-114)

**Comment by jdavies-st** [comment]
@eslavich I added the most recent deprecations to the list above. If you feel these should not be removed in 3.0, feel free to move them further out to a separate issue for 4.0.

Feel free to edit and add new ones as you deprecate more things!

**Comment by braingram** [comment]
All but the `software` change listed above were included in asdf 3.0.0. I reopened https://github.com/asdf-format/asdf/issues/709 to track the `software` issue.
